### ISSUE TITLE
Create small librairy with only doctype variable ?

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-doctypes#7]
index.js:
```
export const FILES_DOCTYPE = 'io.cozy.files'
export const BANK_ACCOUNTS_DOCTYPE = 'io.cozy.bank.accounts'
export const BANK_OPERATIONS_DOCTYPE = 'io.cozy.bank.operations'
export const PHOTO_ALBUMS_DOCTYPE = 'io.cozy.photos.albums'
```

In Cozy app:
```
import {  FILES_DOCTYPE } from 'cozy-doctype'
```

**Comment by ptbrowne** [comment]
Yes please !

**Comment by gregorylegarec** [comment]
If you mean maintaining a dependency and having to update this dependency every time a new doctype is needed, I say nope.

If you mean using an internal lib into our mono-repo, I say yep.

**Comment by kosssi** [comment]
Je pensais faire ça dans une nouvelle librairie dans ce dépôt.
La différence, c'est que l'on crée pas des doctypes tous les jours du coup c'est pas super couteux et le gros avantage que je voyais c'est que en même temps on ajoute la documentation au fur et à mesure.

**Comment by y-lohse** [comment]
Plutôt pour, mais la stack n'allait pas utiliser ce dépôt pour autre chose que de la doc aussi ? Ping @nono au cas où.

**Comment by nono** [comment]
We will use this repository for other things that documentation (describing how to index documents from a doctype in order to do fulltext search for example). But the PR made by @kosssi is not an issue for that.

There was also an idea of extracting some JS code related to a doctype in this repository (models in backbone terms). But with react, it's less clear and we can still do that if we want in this repository (using the same npm packages).
